package com.SymptomCheck.userservice.models;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;

import java.time.Instant;

import static org.junit.jupiter.api.Assertions.*;

class UserDataTest {

    private UserData userData;

    @BeforeEach
    void setUp() {
        userData = new UserData();
    }

    @Nested
    @DisplayName("Getter and Setter Tests")
    class GetterSetterTests {

        @Test
        @DisplayName("should set and get all fields correctly")
        void shouldSetAndGetAllFields() {
            // Given
            String id = "user-123";
            String phoneNumber = "+1234567890";
            String profilePhotoUrl = "https://example.com/photo.jpg";
            Boolean profileComplete = true;
            Long clinicId = 1L;
            Instant createdAt = Instant.now();
            Instant updatedAt = Instant.now().plusSeconds(3600);
            String speciality = "Cardiology";
            String description = "Experienced cardiologist";
            String diploma = "MD, PhD";

            // When
            userData.setId(id);
            userData.setPhoneNumber(phoneNumber);
            userData.setProfilePhotoUrl(profilePhotoUrl);
            userData.setProfileComplete(profileComplete);
            userData.setClinicId(clinicId);
            userData.setCreatedAt(createdAt);
            userData.setUpdatedAt(updatedAt);
            userData.setSpeciality(speciality);
            userData.setDescription(description);
            userData.setDiploma(diploma);

            // Then
            assertEquals(id, userData.getId());
            assertEquals(phoneNumber, userData.getPhoneNumber());
            assertEquals(profilePhotoUrl, userData.getProfilePhotoUrl());
            assertEquals(profileComplete, userData.getProfileComplete());
            assertEquals(clinicId, userData.getClinicId());
            assertEquals(createdAt, userData.getCreatedAt());
            assertEquals(updatedAt, userData.getUpdatedAt());
            assertEquals(speciality, userData.getSpeciality());
            assertEquals(description, userData.getDescription());
            assertEquals(diploma, userData.getDiploma());
        }
    }

    @Nested
    @DisplayName("Default Value Tests")
    class DefaultValueTests {

        @Test
        @DisplayName("should have false as default profileComplete")
        void shouldHaveFalseAsDefaultProfileComplete() {
            // When creating new instance
            UserData newUserData = new UserData();

            // Then
            assertFalse(newUserData.getProfileComplete());
            assertNotNull(newUserData.getCreatedAt());
        }

        @Test
        @DisplayName("should have auto-generated createdAt timestamp")
        void shouldHaveAutoGeneratedCreatedAt() {
            // When creating new instance
            UserData newUserData = new UserData();

            // Then
            assertNotNull(newUserData.getCreatedAt());
            assertTrue(newUserData.getCreatedAt().isBefore(Instant.now().plusSeconds(1)));
            assertTrue(newUserData.getCreatedAt().isAfter(Instant.now().minusSeconds(1)));
        }

        @Test
        @DisplayName("should have null updatedAt by default")
        void shouldHaveNullUpdatedAtByDefault() {
            // When creating new instance
            UserData newUserData = new UserData();

            // Then
            assertNull(newUserData.getUpdatedAt());
        }
    }

    @Nested
    @DisplayName("Equals and HashCode Tests")
    class EqualsHashCodeTests {

        @Test
        @DisplayName("should not be equal when IDs differ")
        void shouldNotBeEqualWhenIdsDiffer() {
            // Given
            UserData userData1 = new UserData();
            userData1.setId("id-1");

            UserData userData2 = new UserData();
            userData2.setId("id-2");

            // Then
            assertNotEquals(userData1, userData2);
        }

        @Test
        @DisplayName("should not be equal when compared with null")
        void shouldNotBeEqualWhenComparedWithNull() {
            // Given
            UserData userData = new UserData();
            userData.setId("test-id");

            // Then
            assertNotEquals(null, userData);
        }

        @Test
        @DisplayName("should not be equal when compared with different class")
        void shouldNotBeEqualWhenComparedWithDifferentClass() {
            // Given
            UserData userData = new UserData();
            userData.setId("test-id");

            // Then
            assertNotEquals("string-object", userData);
        }
    }

    @Nested
    @DisplayName("ToString Tests")
    class ToStringTests {

        @Test
        @DisplayName("should generate non-null toString")
        void shouldGenerateNonNullToString() {
            // Given
            userData.setId("user-123");
            userData.setSpeciality("Dermatology");
            userData.setProfileComplete(true);

            // When
            String toStringResult = userData.toString();

            // Then
            assertNotNull(toStringResult);
            assertTrue(toStringResult.contains("user-123"));
            assertTrue(toStringResult.contains("Dermatology"));
            assertTrue(toStringResult.contains("profileComplete=true"));
        }

        @Test
        @DisplayName("toString should handle null fields gracefully")
        void toStringShouldHandleNullFields() {
            // Given - userData with default null fields

            // When
            String toStringResult = userData.toString();

            // Then
            assertNotNull(toStringResult);
            // Should not throw NullPointerException
        }
    }

    @Nested
    @DisplayName("Edge Case Tests")
    class EdgeCaseTests {

        @Test
        @DisplayName("should handle null ID in equals")
        void shouldHandleNullIdInEquals() {
            // Given
            UserData userData1 = new UserData();
            userData1.setId(null);

            UserData userData2 = new UserData();
            userData2.setId("some-id");

            // Then
            assertNotEquals(userData1, userData2);
        }

        @Test
        @DisplayName("should handle both null IDs in equals")
        void shouldHandleBothNullIdsInEquals() {
            // Given
            UserData userData1 = new UserData();
            userData1.setId(null);

            UserData userData2 = new UserData();
            userData2.setId(null);

            // Then
            assertEquals(userData1, userData2);
        }
    }
}